// <auto-generated />
using System;
using GerenciadorDeTarefas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GerenciadorDeTarefas.Context.Migrations
{
    [DbContext(typeof(ContextoDeDados))]
    [Migration("20201020141339_BancoInicial")]
    partial class BancoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Equipes.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Funcionalidades.Objetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Adicionado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Finalizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Previsao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdProjeto");

                    b.ToTable("Funcionalidades");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.ManyToMany.EquipeUsuario", b =>
                {
                    b.Property<int>("IdEquipe")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdEquipe", "IdUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("EquipeUsuario");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Pessoas.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Projetos.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("IdProjeto")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdProjeto");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Tarefas.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Adicionado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Finalizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdObjetivo")
                        .HasColumnType("integer");

                    b.Property<int>("IdProjeto")
                        .HasColumnType("integer");

                    b.Property<int>("IdTarefaPrincipal")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Previsao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdObjetivo");

                    b.HasIndex("IdProjeto");

                    b.HasIndex("IdTarefaPrincipal");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<int>("IdPessoa")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.HasKey("IdPessoa");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Funcionalidades.Objetivo", b =>
                {
                    b.HasOne("GerenciadorDeTarefas.Domain.Projetos.Projeto", "Projeto")
                        .WithMany("Funcionalidades")
                        .HasForeignKey("IdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.ManyToMany.EquipeUsuario", b =>
                {
                    b.HasOne("GerenciadorDeTarefas.Domain.Equipes.Equipe", "Equipe")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEquipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorDeTarefas.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany("Equipes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Projetos.Projeto", b =>
                {
                    b.HasOne("GerenciadorDeTarefas.Domain.Equipes.Equipe", "Equipe")
                        .WithMany("Projetos")
                        .HasForeignKey("IdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Tarefas.Tarefa", b =>
                {
                    b.HasOne("GerenciadorDeTarefas.Domain.Funcionalidades.Objetivo", "Objetivo")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdObjetivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorDeTarefas.Domain.Projetos.Projeto", "Projeto")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorDeTarefas.Domain.Tarefas.Tarefa", "TarefaPrincipal")
                        .WithMany("SubTarefas")
                        .HasForeignKey("IdTarefaPrincipal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("GerenciadorDeTarefas.Domain.Pessoas.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("GerenciadorDeTarefas.Domain.Usuarios.Usuario", "IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
